name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - "config/LiNEA40.keymap"
      - "keymap_drawer.config.yaml"

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Keymap Drawer
        run: pip install keymap-drawer

      - name: Parse and Draw
        run: |
          # 1. config直下のファイルを指定してYAML化 (詳細ログ付き)
          # --verbose をつけることで、なぜエラーになったか原因を吐き出させます
          keymap --verbose parse -z config/LiNEA40.keymap > keymap.yaml

          # 2. YAMLからSVGを描画
          keymap --verbose draw keymap.yaml > keymap.svg

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add keymap.svg keymap.yaml
          git commit -m "Update keymap visualization" || exit 0
          git push
